#!/bin/bash
# One-time, per-clone setup of the dev container's git identity and SSH credentials.
#
# Run on the host (or inside the container) once after creating a project:
#     ./scripts/setup-identity.sh
#
# Writes .devcontainer/devcontainer.env and (optionally) an SSH key under
# .devcontainer/ssh/ -- both git-ignored. Re-run any time to change values.
#
# For the HTTPS + Personal Access Token alternative, see the README; this script
# focuses on the recommended SSH flow.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="$REPO_ROOT/.devcontainer/devcontainer.env"
SSH_DIR="$REPO_ROOT/.devcontainer/ssh"

umask 077

echo "== Dev container identity setup =="
echo "Press Enter to accept the [default] taken from your host git config."
echo

default_name="$(git config --get user.name 2>/dev/null || true)"
default_email="$(git config --get user.email 2>/dev/null || true)"

read -rp "Git user name [${default_name}]: " name
name="${name:-$default_name}"
read -rp "Git user email [${default_email}]: " email
email="${email:-$default_email}"

mkdir -p "$REPO_ROOT/.devcontainer"
cat >"$ENV_FILE" <<EOF
# Per-project git identity for the dev container (git-ignored).
# Generated by scripts/setup-identity.sh -- re-run to change.
GIT_USER_NAME="${name}"
GIT_USER_EMAIL="${email}"
GIT_CREDENTIAL_HOST="github.com"
EOF
chmod 600 "$ENV_FILE"
echo "Wrote $ENV_FILE"
echo

echo "== SSH credentials =="
mkdir -p "$SSH_DIR"
existing_key=""
for f in "$SSH_DIR"/*; do
    [ -f "$f" ] || continue
    case "$(basename "$f")" in
        *.pub | known_hosts | config | *.md | .gitkeep) continue ;;
    esac
    existing_key="$f"
    break
done

if [ -n "$existing_key" ]; then
    echo "Found existing key: $existing_key"
    echo "It will be installed inside the container on create."
else
    read -rp "No SSH key found. Generate a per-project deploy key now? [y/N]: " gen
    if [[ "$gen" =~ ^[Yy]$ ]]; then
        keyfile="$SSH_DIR/id_ed25519"
        ssh-keygen -t ed25519 -N "" -C "$(basename "$REPO_ROOT")-devcontainer" -f "$keyfile"
        chmod 600 "$keyfile"
        echo
        echo "Public key -- add this to the client's GitHub repo as a Deploy Key"
        echo "(Settings -> Deploy keys -> Add deploy key; tick 'Allow write access'):"
        echo "----------------------------------------------------------------------"
        cat "$keyfile.pub"
        echo "----------------------------------------------------------------------"
    else
        echo "Skipped. Drop a client-provided private key into $SSH_DIR/ later,"
        echo "or re-run this script to generate one."
    fi
fi

echo
echo "Done. Reopen/rebuild the dev container, or apply now with:"
echo "    bash .devcontainer/setup_git.sh"
